name: FeatureManagement-JavaScript CI

on:
  push:
    branches:
      - main
      - preview
      - release/*
  pull_request:
    branches:
      - main
      - preview
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    defaults:
      run:
        working-directory: src/feature-management

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/feature-management/package-lock.json

    - name: Install dependencies
      run: npm ci
      working-directory: src/feature-management

    - name: Run lint check for feature-management
      run: npm run lint
      working-directory: src/feature-management

    - name: Build feature-management
      run: npm run build
      working-directory: src/feature-management

    - name: Run tests
      run: npm run test
      working-directory: src/feature-management

    - name: Run browser tests
      run: npm run test-browser
      working-directory: src/feature-management

    - name: Build feature-management-applicationinsights-browser
      run: npm run build
      working-directory: src/feature-management-applicationinsights-browser

    - name: Run lint check for feature-management-applicationinsights-browser
      run: npm run lint
      working-directory: src/feature-management-applicationinsights-browser

    - name: Build feature-management-applicationinsights-node
      run: npm run build
      working-directory: src/feature-management-applicationinsights-node

    - name: Run lint check for feature-management-applicationinsights-node
      run: npm run lint
      working-directory: src/feature-management-applicationinsights-node
