name: FeatureManagement-JavaScriptProvider CI

on:
  push:
    branches:
      - main
      - preview
      - release/*
  pull_request:
    branches:
      - main
      - preview
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    defaults:
      run:
        working-directory: sdk/feature-management

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: sdk/feature-management/package-lock.json
    
    - name: Install dependencies
      run: npm ci
      working-directory: sdk/feature-management

    - name: Run lint check 1
      run: npm run lint
      working-directory: sdk/feature-management

    - name: Run build
      run: npm run build
      working-directory: sdk/feature-management

    - name: Run tests
      run: npm run test
      working-directory: sdk/feature-management

    - name: Run browser tests
      run: npm run test-browser
      working-directory: sdk/feature-management

    - name: Link and install dependencies
      run: npm link ../feature-management
      working-directory: sdk/feature-management-applicationinsights-browser

    - name: Run lint check 2
      run: npm run lint
      working-directory: sdk/feature-management-applicationinsights-browser

    - name: Run build
      run: npm run build
      working-directory: sdk/feature-management-applicationinsights-browser

    
